language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-text
  - ./vendor/bin/phpcs lib/Wave --standard=psr2 --ignore=lib/Wave/View/Stream.php

after_script:
  - ./vendor/bin/coveralls -v
