language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install

script:
  - mkdir -p build/reports
  - mkdir -p build/coverage/html
  - phpunit --coverage-text
  - ./vendor/bin/phpcs src --standard=psr2

after_script:
  - ./vendor/bin/coveralls -v
