language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer require satooshi/php-coveralls:dev-master --no-update --dev
  - composer install

script:
  - mkdir -p build/reports
  - mkdir -p build/coverage/html
  - phpunit --coverage-text
  - ./vendor/bin/phpcbf src/Wave --standard=psr2
  - ./vendor/bin/phpcs src/Wave --standard=psr2
  - ./vendor/bin/phpmd src/Wave text cleancode,codesize,controversial,design,naming,unusedcode

after_script:
  - ./vendor/bin/coveralls -v
